#!/usr/bin/env python3
"""
Extract bulletspread / firespreadmult from retail MOHAA weapon .tik files in pk3 archives.
Emits a C fragment for cg_crosshair_spread.c weapon profile table.

Usage:
  python3 extract_weapon_spread.py /path/to/mohaa/main > weapon_profiles.inc
"""

from __future__ import annotations

import re
import sys
import zipfile
from pathlib import Path

# Config-string weapon display name -> pak tik basename (models/weapons/<name>.tik)
WEAPON_TIK_MAP = {
    "Thompson": "thompsonsmg",
    "MP40": "mp40",
    "BAR": "bar",
    "M1 Garand": "m1_garand",
    "Mauser KAR 98K": "kar98",
    "StG 44": "mp44",
    "Colt 45": "colt45",
    "Walther P38": "p38",
    "Springfield '03 Sniper": "springfield",
    "KAR98 - Sniper": "kar98_sniper",
    "Thompson": "thompsonsmg",
    "PPSH SMG": "ppsh",
    "FG 42": "fg42",
    "Lee-Enfield": "enfield",
    "Webley Revolver": "webley",
    "Frag Grenade": None,
    "Panzerfaust": None,
    "Bazooka": None,
}


def parse_floats(line: str) -> list[float]:
    return [float(x) for x in re.findall(r"-?\d+\.?\d*", line)]


def read_tik_from_pk3(main_dir: Path, tik_name: str) -> str | None:
    rel = f"models/weapons/{tik_name}.tik"
    for pak in sorted(main_dir.glob("Pak*.pk3")) + sorted(main_dir.glob("pak*.pk3")):
        try:
            with zipfile.ZipFile(pak) as zf:
                if rel in zf.namelist():
                    return zf.read(rel).decode("latin-1", errors="replace")
        except OSError:
            continue
    return None


def extract_spread(text: str, use_dm: bool) -> dict | None:
    spread_key = "dmbulletspread" if use_dm else "bulletspread"
    fire_key = "dmfirespreadmult" if use_dm else "firespreadmult"
    spread_line = None
    fire_line = None
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("//"):
            continue
        if spread_line is None and spread_key in stripped.split():
            spread_line = stripped
        if fire_line is None and fire_key in stripped.split():
            fire_line = stripped
    if spread_line is None and "bulletspread" in text:
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("bulletspread"):
                spread_line = stripped
                break
    if fire_line is None and "firespreadmult" in text:
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("firespreadmult"):
                fire_line = stripped
                break
    if not spread_line:
        return None
    spread = parse_floats(spread_line)
    if len(spread) < 4:
        return None
    fire = parse_floats(fire_line) if fire_line else [0.0, 0.0, 0.0, 0.0]
    while len(fire) < 4:
        fire.append(0.0)
    return {
        "min_x": spread[0],
        "min_y": spread[1],
        "max_x": spread[2],
        "max_y": spread[3],
        "fire_amount": fire[0],
        "fire_falloff": fire[1],
        "fire_cap": fire[2],
        "fire_timecap": fire[3],
    }


def emit_profile(name: str, data: dict) -> str:
    esc = name.replace("\\", "\\\\").replace('"', '\\"')
    return (
        f'\t{{ "{esc}", '
        f'{{ {data["min_x"]:.4f}f, {data["min_y"]:.4f}f, '
        f'{data["max_x"]:.4f}f, {data["max_y"]:.4f}f, '
        f'{data["fire_amount"]:.4f}f, {data["fire_falloff"]:.4f}f, '
        f'{data["fire_cap"]:.4f}f, {data["fire_timecap"]:.4f}f, 1.0f }} }},'
    )


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: extract_weapon_spread.py <mohaa/main>", file=sys.stderr)
        return 1
    main_dir = Path(sys.argv[1])
    use_dm = True
    print("/* Generated by extract_weapon_spread.py — DM spread values */")
    print("static const xspread_weapon_entry_t g_xspreadWeaponProfiles[] = {")
    seen: set[str] = set()
    for display_name, tik in WEAPON_TIK_MAP.items():
        if not tik or display_name in seen:
            continue
        seen.add(display_name)
        text = read_tik_from_pk3(main_dir, tik)
        if not text:
            print(f'\t/* missing tik: {display_name} -> {tik} */', file=sys.stderr)
            continue
        data = extract_spread(text, use_dm)
        if not data:
            data = extract_spread(text, False)
        if not data:
            print(f'\t/* no spread in {display_name} */', file=sys.stderr)
            continue
        print(emit_profile(display_name, data))
    print("};")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
